/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIS;

import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import static javax.swing.UIManager.get;

/**
 *
 * @author Posilandia
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        LoadFileButton = new javax.swing.JButton();
        SaveFileButton = new javax.swing.JButton();
        AddCityButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        SavedFileName = new javax.swing.JTextField();
        SourceFileName = new javax.swing.JTextField();
        SourceFileLabel = new javax.swing.JLabel();
        SavedFileLabel = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.lightGray);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Exit.setBackground(new java.awt.Color(255, 255, 255));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/close.png"))); // NOI18N
        Exit.setText("jButton1");
        Exit.setBorder(null);
        Exit.setBorderPainted(false);
        Exit.setMinimumSize(new java.awt.Dimension(10, 10));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 30, 60, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 10, 10));
        jLabel1.setText("Ants Systems");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("----------------------------\n\n             No\n             hay\n       informacion\n          cargada \n             en \n             el \n          sistema\n----------------------------");
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 130, 380));

        LoadFileButton.setText("Cargar Archivo");
        getContentPane().add(LoadFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, -1));

        SaveFileButton.setText("Guardar archivo");
        getContentPane().add(SaveFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 140, -1));

        AddCityButton.setText("Agregar ciudad");
        getContentPane().add(AddCityButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 140, -1));

        jButton4.setText("Eliminar ciudad");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, -1));

        jButton5.setText("Simular");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 140, 50));

        SavedFileName.setText("---No ha guardado el archivo---");
        getContentPane().add(SavedFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 260, -1));

        SourceFileName.setText(" ----No Hay ningun archivo abierto---");
        SourceFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SourceFileNameActionPerformed(evt);
            }
        });
        getContentPane().add(SourceFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 260, -1));

        SourceFileLabel.setForeground(new java.awt.Color(51, 51, 51));
        SourceFileLabel.setText("Archivo origen:");
        getContentPane().add(SourceFileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 240, -1));

        SavedFileLabel.setForeground(new java.awt.Color(51, 51, 51));
        SavedFileLabel.setText("Archivo destino:");
        getContentPane().add(SavedFileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 250, -1));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Background1.jpg"))); // NOI18N
        Background.setLabelFor(this);
        Background.setToolTipText("");
        Background.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Background.setOpaque(true);
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void SourceFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SourceFileNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SourceFileNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCityButton;
    private javax.swing.JLabel Background;
    private javax.swing.JButton Exit;
    private javax.swing.JButton LoadFileButton;
    private javax.swing.JButton SaveFileButton;
    private javax.swing.JLabel SavedFileLabel;
    private javax.swing.JTextField SavedFileName;
    private javax.swing.JLabel SourceFileLabel;
    private javax.swing.JTextField SourceFileName;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    /**
     * *
     *
     * public class Background extends JPanel{
     *
     * public void image (Graphics g){ ImageIcon imagen = new
     * ImageIcon(get.class().getResource("Pictures\Background1.jpg"));
     * g.drawImage(imagen.getImage(),0,0,getWidth(),getHeight(),this);
     * setOpaque(false); super.paint(g); } }
**
     */
}
