/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIS;

/**
 *
 * @author Posilandia
 */
public class SimulationWindow extends javax.swing.JFrame {

    /**
     * Creates new form SimulationWindow
     */
    public SimulationWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        windowTitle = new javax.swing.JLabel();
        antsLabel = new javax.swing.JLabel();
        ciclesLabel = new javax.swing.JLabel();
        finalCituLabel = new javax.swing.JLabel();
        valuesTitleLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        defaultLabel = new javax.swing.JLabel();
        pLabel = new javax.swing.JLabel();
        aLabel = new javax.swing.JLabel();
        bLabel = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Ciudad de Inicio");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        windowTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        windowTitle.setForeground(new java.awt.Color(51, 51, 51));
        windowTitle.setText("Nueva Simulacion");
        jPanel1.add(windowTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 40));

        antsLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        antsLabel.setForeground(new java.awt.Color(51, 51, 51));
        antsLabel.setText("Cantidad de hormigas:");
        jPanel1.add(antsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        ciclesLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ciclesLabel.setForeground(new java.awt.Color(51, 51, 51));
        ciclesLabel.setText("Cantidad de ciclos a realizar: ");
        jPanel1.add(ciclesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        finalCituLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        finalCituLabel.setForeground(new java.awt.Color(51, 51, 51));
        finalCituLabel.setText("Ciudad Final");
        jPanel1.add(finalCituLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        valuesTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        valuesTitleLabel.setForeground(new java.awt.Color(51, 51, 51));
        valuesTitleLabel.setText("Valores de a, b, c:");
        jPanel1.add(valuesTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setText("0");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 60, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, 30));

        defaultLabel.setForeground(new java.awt.Color(51, 51, 51));
        defaultLabel.setText("Coloque 0 para utilizar el valor default");
        jPanel1.add(defaultLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        pLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pLabel.setForeground(new java.awt.Color(51, 51, 51));
        pLabel.setText("p");
        jPanel1.add(pLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 20, -1));

        aLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        aLabel.setForeground(new java.awt.Color(51, 51, 51));
        aLabel.setText("a");
        jPanel1.add(aLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 20, -1));

        bLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bLabel.setForeground(new java.awt.Color(51, 51, 51));
        bLabel.setText("b");
        jPanel1.add(bLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 20, -1));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField6.setText("0");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 60, 40));

        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField7.setText("0");
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 60, 40));

        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField8.setText("0");
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 60, 40));

        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField9.setText("0");
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 60, 40));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/Background1.jpg"))); // NOI18N
        backgroundLabel.setText("a");
        jPanel1.add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimulationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimulationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimulationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimulationWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aLabel;
    private javax.swing.JLabel antsLabel;
    private javax.swing.JLabel bLabel;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JLabel ciclesLabel;
    private javax.swing.JLabel defaultLabel;
    private javax.swing.JLabel finalCituLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel pLabel;
    private javax.swing.JLabel valuesTitleLabel;
    private javax.swing.JLabel windowTitle;
    // End of variables declaration//GEN-END:variables
}
